import {
  AppleIcon,
  AvocadoIcon,
  BananaIcon,
  BbqGrillIcon,
  BeanIcon,
  BeerIcon,
  Bread01Icon,
  BroccoliIcon,
  CakeIcon,
  CakeSliceIcon,
  CandyIcon,
  CarrotIcon,
  CheeseCake01Icon,
  CheeseCake02Icon,
  CheeseIcon,
  CherryIcon,
  ChocolateIcon,
  CinnamonRollIcon,
  CitrusIcon,
  Coffee02Icon,
  CookieIcon,
  CookingPotIcon,
  CornIcon,
  CrabIcon,
  CroissantIcon,
  Cupcake01Icon,
  DessertIcon,
  DonutIcon,
  DrinkIcon,
  DropletIcon,
  DrumstickIcon,
  EggFriedIcon,
  EggsIcon,
  FishIcon,
  FrenchFries01Icon,
  GlassWaterIcon,
  GrapesIcon,
  HamIcon,
  Hamburger01Icon,
  Honey01Icon,
  HotdogIcon,
  IceCream02Icon,
  IceCubesIcon,
  Leaf01Icon,
  LeafyGreenIcon,
  MilkBottleIcon,
  MilkCartonIcon,
  MilkCoconutIcon,
  MilkOatIcon,
  MushroomIcon,
  NoodlesIcon,
  NutIcon,
  OctopusIcon,
  OrangeIcon,
  PepperIcon,
  PieIcon,
  PillBottleIcon,
  Pizza01Icon,
  PopcornIcon,
  PopsicleIcon,
  PumpkinIcon,
  RiceBowl01Icon,
  SaladIcon,
  SandwichIcon,
  SausageIcon,
  ShellfishIcon,
  ShrimpIcon,
  SoftDrink01Icon,
  SoupIcon,
  SpaghettiIcon,
  SteakIcon,
  Sushi01Icon,
  Taco01Icon,
  Taco02Icon,
  TeaIcon,
  WatermelonIcon,
  WheatIcon,
  YogurtIcon,
} from "@hugeicons/core-free-icons"

export type Icon = typeof AppleIcon

/**
 * A food and the names it goes by, in Portuguese and English. Matching ignores case, accents and
 * hyphens, and a name also matches its plural in -s or -es, so list only the irregular plurals
 * (pães, cherries). The hue is the colour of the food itself. A dish is what a recipe makes: a
 * title that names one shows it before any ingredient, so "banana bread" is bread.
 */
export type Food = { icon: Icon; hue: number; names: string[]; dish?: boolean }

/** When two foods share a name at the same spot, the first one here wins. */
export const FOODS: Food[] = [
  { icon: EggsIcon, hue: 85, names: ["ovo", "egg", "gema", "yolk", "clara", "egg white"] },
  { icon: MilkBottleIcon, hue: 235, names: ["leite", "milk", "leite condensado", "buttermilk"] },
  {
    icon: MilkCartonIcon,
    hue: 250,
    names: [
      "creme de leite",
      "nata",
      "chantilly",
      "chantili",
      "cream",
      "heavy cream",
      "whipping cream",
      "double cream",
      "sour cream",
      "crème fraîche",
      "half and half",
    ],
  },
  {
    icon: MilkOatIcon,
    hue: 75,
    names: [
      "leite vegetal",
      "leite de aveia",
      "leite de amêndoas",
      "leite de soja",
      "leite de arroz",
      "leite de castanha",
      "plant milk",
      "oat milk",
      "almond milk",
      "soy milk",
      "rice milk",
    ],
  },
  {
    icon: MilkCoconutIcon,
    hue: 70,
    names: [
      "coco",
      "coconut",
      "leite de coco",
      "creme de coco",
      "coco ralado",
      "água de coco",
      "coconut milk",
    ],
  },
  { icon: YogurtIcon, hue: 330, names: ["iogurte", "yogurt", "yoghurt", "coalhada", "kefir"] },
  {
    icon: CheeseIcon,
    hue: 90,
    names: [
      "queijo",
      "cheese",
      "cream cheese",
      "requeijão",
      "catupiry",
      "mussarela",
      "muçarela",
      "mozzarella",
      "parmesão",
      "parmesan",
      "parmigiano",
      "pecorino",
      "ricota",
      "ricotta",
      "provolone",
      "gorgonzola",
      "cheddar",
      "brie",
      "camembert",
      "feta",
      "mascarpone",
      "cottage",
      "gruyère",
      "emmental",
      "burrata",
      "halloumi",
    ],
  },

  { icon: BananaIcon, hue: 95, names: ["banana", "plantain"] },
  { icon: CitrusIcon, hue: 115, names: ["limão", "limões", "lima", "lemon", "lime"] },
  {
    icon: OrangeIcon,
    hue: 60,
    names: [
      "laranja",
      "orange",
      "tangerina",
      "tangerine",
      "mexerica",
      "bergamota",
      "clementina",
      "clementine",
      "mandarin",
    ],
  },
  { icon: AppleIcon, hue: 25, names: ["maçã", "apple"] },
  {
    icon: CherryIcon,
    hue: 15,
    names: [
      "cereja",
      "cherry",
      "cherries",
      "morango",
      "strawberry",
      "strawberries",
      "framboesa",
      "raspberry",
      "raspberries",
      "amora",
      "blackberry",
      "blackberries",
      "mirtilo",
      "blueberry",
      "blueberries",
      "cranberry",
      "cranberries",
      "groselha",
      "frutas vermelhas",
      "berry",
      "berries",
    ],
  },
  { icon: GrapesIcon, hue: 310, names: ["uva", "grape", "uva passa", "passas", "raisin"] },
  { icon: WatermelonIcon, hue: 20, names: ["melancia", "watermelon", "melão", "melões", "melon"] },
  { icon: AvocadoIcon, hue: 135, names: ["abacate", "avocado", "guacamole"] },

  {
    icon: PumpkinIcon,
    hue: 55,
    names: ["abóbora", "moranga", "cabotiá", "pumpkin", "squash", "butternut"],
  },
  { icon: CarrotIcon, hue: 50, names: ["cenoura", "carrot"] },
  {
    icon: CornIcon,
    hue: 95,
    names: [
      "milho",
      "corn",
      "fubá",
      "farinha de milho",
      "amido de milho",
      "maisena",
      "maizena",
      "cornmeal",
      "cornstarch",
      "corn starch",
      "polenta",
    ],
  },
  { icon: PopcornIcon, hue: 85, names: ["pipoca", "popcorn", "milho de pipoca"] },
  {
    icon: PepperIcon,
    hue: 30,
    names: [
      "pimentão",
      "pimentões",
      "pimenta dedo-de-moça",
      "dedo-de-moça",
      "pimenta biquinho",
      "pimenta calabresa",
      "malagueta",
      "jalapeño",
      "habanero",
      "chili",
      "chilli",
      "chili flakes",
      "bell pepper",
      "red pepper",
      "green pepper",
      "yellow pepper",
      "red pepper flakes",
    ],
  },
  {
    icon: BroccoliIcon,
    hue: 140,
    names: ["brócolis", "brócoli", "broccoli", "couve-flor", "cauliflower"],
  },
  {
    icon: LeafyGreenIcon,
    hue: 145,
    names: [
      "alface",
      "lettuce",
      "rúcula",
      "arugula",
      "espinafre",
      "spinach",
      "couve",
      "kale",
      "repolho",
      "cabbage",
      "agrião",
      "watercress",
      "acelga",
      "chard",
      "escarola",
      "chicória",
      "endívia",
    ],
  },
  {
    icon: Leaf01Icon,
    hue: 150,
    names: [
      "manjericão",
      "basil",
      "salsa",
      "salsinha",
      "parsley",
      "cebolinha",
      "chives",
      "coentro",
      "cilantro",
      "coriander",
      "hortelã",
      "mint",
      "alecrim",
      "rosemary",
      "tomilho",
      "thyme",
      "louro",
      "bay leaf",
      "sálvia",
      "sage",
      "orégano",
      "oregano",
      "endro",
      "dill",
      "estragão",
      "tarragon",
      "cheiro-verde",
      "ervas",
      "herbs",
    ],
  },
  {
    icon: MushroomIcon,
    hue: 60,
    names: [
      "cogumelo",
      "mushroom",
      "champignon",
      "shiitake",
      "shitake",
      "shimeji",
      "portobello",
      "funghi",
    ],
  },
  {
    icon: BeanIcon,
    hue: 40,
    names: [
      "feijão",
      "feijões",
      "bean",
      "vagem",
      "green bean",
      "grão-de-bico",
      "chickpea",
      "garbanzo",
      "lentilha",
      "lentil",
      "ervilha",
      "pea",
      "soja",
      "soy",
      "soybean",
      "edamame",
      "fava",
    ],
  },
  {
    icon: NutIcon,
    hue: 55,
    names: [
      "noz",
      "walnut",
      "nut",
      "amêndoa",
      "almond",
      "amendoim",
      "peanut",
      "pasta de amendoim",
      "manteiga de amendoim",
      "peanut butter",
      "castanha",
      "chestnut",
      "castanha de caju",
      "cashew",
      "castanha-do-pará",
      "brazil nut",
      "avelã",
      "hazelnut",
      "pistache",
      "pistachio",
      "macadâmia",
      "macadamia",
      "pecã",
      "pecan",
    ],
  },

  {
    icon: ChocolateIcon,
    hue: 45,
    names: [
      "chocolate",
      "cacau",
      "cocoa",
      "cacao",
      "nutella",
      "brigadeiro",
      "trufa",
      "truffle",
      "bombom",
      "fudge",
    ],
  },
  {
    icon: Honey01Icon,
    hue: 80,
    names: ["mel", "honey", "melado", "maple", "xarope", "syrup", "agave", "glucose"],
  },
  {
    icon: CandyIcon,
    hue: 340,
    names: [
      "açúcar",
      "sugar",
      "adoçante",
      "sweetener",
      "rapadura",
      "caramelo",
      "caramel",
      "doce de leite",
      "dulce de leche",
      "marshmallow",
      "granulado",
      "sprinkles",
      "confeito",
    ],
  },
  {
    icon: PillBottleIcon,
    hue: 35,
    names: [
      "pimenta",
      "pimenta-do-reino",
      "pepper",
      "black pepper",
      "white pepper",
      "peppercorn",
      "páprica",
      "paprika",
      "colorau",
      "cominho",
      "cumin",
      "canela",
      "cinnamon",
      "noz-moscada",
      "nutmeg",
      "cravo",
      "clove",
      "açafrão",
      "saffron",
      "cúrcuma",
      "turmeric",
      "curry",
      "garam masala",
      "tempero",
      "seasoning",
      "especiaria",
      "spice",
    ],
  },
  {
    icon: PillBottleIcon,
    hue: 235,
    names: [
      "sal",
      "salt",
      "sal grosso",
      "flor de sal",
      "fermento",
      "levedura",
      "yeast",
      "bicarbonato",
      "baking soda",
      "baking powder",
      "cremor tártaro",
      "cream of tartar",
    ],
  },
  {
    icon: DropletIcon,
    hue: 100,
    names: [
      "azeite",
      "óleo",
      "oil",
      "olive oil",
      "coconut oil",
      "óleo de coco",
      "peanut oil",
      "sesame oil",
      "óleo de gergelim",
    ],
  },
  {
    icon: DropletIcon,
    hue: 25,
    names: [
      "vinagre",
      "vinegar",
      "balsâmico",
      "balsamic",
      "shoyu",
      "soy sauce",
      "molho de soja",
      "molho inglês",
      "worcestershire",
      "fish sauce",
      "molho de peixe",
      "molho de pimenta",
      "hot sauce",
      "tabasco",
    ],
  },
  { icon: GlassWaterIcon, hue: 225, names: ["água", "water", "água com gás", "sparkling water"] },
  { icon: IceCubesIcon, hue: 215, names: ["gelo", "ice", "ice cube"] },
  { icon: TeaIcon, hue: 130, names: ["chá", "tea", "matcha", "chai"] },
  {
    icon: DrinkIcon,
    hue: 330,
    names: [
      "drink",
      "drinque",
      "coquetel",
      "cocktail",
      "caipirinha",
      "caipiroska",
      "mojito",
      "margarita",
      "negroni",
      "spritz",
      "sangria",
      "piña colada",
      "vinho",
      "wine",
      "espumante",
      "champagne",
      "prosecco",
      "vermute",
      "vermouth",
      "marsala",
      "cachaça",
      "rum",
      "vodka",
      "gin",
      "tequila",
      "licor",
      "liqueur",
      "conhaque",
      "brandy",
      "cognac",
      "whisky",
      "whiskey",
      "saquê",
      "sake",
    ],
  },
  { icon: BeerIcon, hue: 75, names: ["cerveja", "beer", "stout", "lager"] },
  {
    icon: WheatIcon,
    hue: 75,
    names: [
      "farinha",
      "flour",
      "bread flour",
      "trigo",
      "wheat",
      "aveia",
      "oat",
      "centeio",
      "rye",
      "cevada",
      "barley",
      "semolina",
      "sêmola",
      "amido",
      "starch",
      "polvilho",
      "tapioca",
      "farelo",
      "bran",
      "granola",
      "quinoa",
    ],
  },

  {
    icon: SteakIcon,
    hue: 25,
    names: [
      "carne",
      "beef",
      "carne moída",
      "ground beef",
      "mince",
      "bife",
      "steak",
      "picanha",
      "alcatra",
      "patinho",
      "acém",
      "maminha",
      "fraldinha",
      "filé mignon",
      "contrafilé",
      "costela",
      "cupim",
      "músculo",
      "lagarto",
      "cordeiro",
      "carneiro",
      "lamb",
      "vitela",
      "veal",
    ],
  },
  {
    icon: DrumstickIcon,
    hue: 50,
    names: [
      "frango",
      "galinha",
      "chicken",
      "coxa",
      "sobrecoxa",
      "asa",
      "asinha",
      "wing",
      "coxinha",
      "nugget",
      "peru",
      "turkey",
      "chester",
      "pato",
      "duck",
      "codorna",
      "quail",
    ],
  },
  {
    icon: HamIcon,
    hue: 10,
    names: [
      "porco",
      "pork",
      "carne de porco",
      "lombo",
      "pernil",
      "costelinha",
      "costela de porco",
      "pork ribs",
      "leitão",
      "presunto",
      "ham",
      "bacon",
      "toucinho",
      "torresmo",
      "pancetta",
      "panceta",
      "prosciutto",
      "copa",
    ],
  },
  {
    icon: SausageIcon,
    hue: 25,
    names: [
      "linguiça",
      "salsicha",
      "sausage",
      "calabresa",
      "paio",
      "chouriço",
      "chorizo",
      "salame",
      "salami",
      "pepperoni",
      "mortadela",
      "bratwurst",
    ],
  },
  {
    icon: FishIcon,
    hue: 225,
    names: [
      "peixe",
      "fish",
      "salmão",
      "salmon",
      "atum",
      "tuna",
      "bacalhau",
      "cod",
      "tilápia",
      "sardinha",
      "sardine",
      "anchova",
      "anchovy",
      "anchovies",
      "merluza",
      "hake",
      "pescada",
      "robalo",
      "sea bass",
      "truta",
      "trout",
      "linguado",
      "haddock",
    ],
  },
  { icon: ShrimpIcon, hue: 35, names: ["camarão", "camarões", "shrimp", "prawn"] },
  { icon: CrabIcon, hue: 25, names: ["caranguejo", "siri", "crab", "lagosta", "lobster"] },
  {
    icon: ShellfishIcon,
    hue: 210,
    names: [
      "frutos do mar",
      "seafood",
      "marisco",
      "mexilhão",
      "mexilhões",
      "mussel",
      "ostra",
      "oyster",
      "vieira",
      "scallop",
      "vôngole",
      "clam",
    ],
  },
  { icon: OctopusIcon, hue: 330, names: ["polvo", "octopus", "lula", "squid", "calamari"] },

  {
    dish: true,
    icon: Bread01Icon,
    hue: 60,
    names: [
      "pão",
      "pães",
      "pão de forma",
      "bread",
      "sliced bread",
      "brioche",
      "focaccia",
      "baguete",
      "baguette",
      "ciabatta",
      "sourdough",
      "bisnaga",
      "bisnaguinha",
      "broa",
      "bagel",
      "bruschetta",
      "torrada",
      "toast",
      "farinha de rosca",
      "breadcrumbs",
      "bread crumbs",
      "panko",
    ],
  },
  { dish: true, icon: CroissantIcon, hue: 70, names: ["croissant"] },
  {
    dish: true,
    icon: CinnamonRollIcon,
    hue: 45,
    names: ["cinnamon roll", "cinnamon bun", "rolinho de canela", "rocambole", "swiss roll"],
  },
  {
    dish: true,
    icon: DessertIcon,
    hue: 50,
    names: ["panqueca", "pancake", "hotcake", "waffle", "crepe"],
  },
  { dish: true, icon: CheeseCake01Icon, hue: 90, names: ["cheesecake"] },
  {
    dish: true,
    icon: CheeseCake02Icon,
    hue: 55,
    names: ["pudim", "flan", "pudding", "manjar", "panna cotta", "crème brûlée"],
  },
  { dish: true, icon: Cupcake01Icon, hue: 340, names: ["cupcake", "muffin", "bolinho"] },
  { dish: true, icon: CakeSliceIcon, hue: 40, names: ["brownie", "blondie"] },
  { dish: true, icon: CakeIcon, hue: 340, names: ["bolo", "cake", "pão de ló"] },
  {
    dish: true,
    icon: PieIcon,
    hue: 45,
    names: [
      "torta",
      "pie",
      "tart",
      "tarte",
      "quiche",
      "empadão",
      "empada",
      "galette",
      "crumble",
      "cobbler",
    ],
  },
  {
    dish: true,
    icon: CookieIcon,
    hue: 55,
    names: ["biscoito", "bolacha", "cookie", "cracker", "wafer", "graham", "shortbread"],
  },
  { dish: true, icon: DonutIcon, hue: 340, names: ["donut", "doughnut", "sonho", "rosquinha"] },
  { dish: true, icon: IceCream02Icon, hue: 340, names: ["sorvete", "ice cream", "gelato"] },
  { dish: true, icon: PopsicleIcon, hue: 15, names: ["picolé", "popsicle", "paleta"] },
  { dish: true, icon: Pizza01Icon, hue: 25, names: ["pizza", "calzone", "esfiha", "esfirra"] },
  {
    dish: true,
    icon: Taco02Icon,
    hue: 45,
    names: ["pastel", "empanada", "gyoza", "guioza", "pierogi"],
  },
  {
    dish: true,
    icon: Hamburger01Icon,
    hue: 40,
    names: ["hambúrguer", "hamburguer", "hamburger", "burger", "cheeseburger"],
  },
  { dish: true, icon: HotdogIcon, hue: 30, names: ["cachorro-quente", "hot dog", "hotdog"] },
  {
    dish: true,
    icon: SandwichIcon,
    hue: 70,
    names: ["sanduíche", "sandwich", "misto-quente", "bauru", "panini", "wrap", "croque monsieur"],
  },
  {
    dish: true,
    icon: Taco01Icon,
    hue: 50,
    names: [
      "taco",
      "taco shell",
      "tortilla",
      "burrito",
      "quesadilla",
      "fajita",
      "enchilada",
      "nachos",
    ],
  },
  {
    dish: true,
    icon: Sushi01Icon,
    hue: 15,
    names: ["sushi", "sashimi", "temaki", "uramaki", "hossomaki", "onigiri", "poke"],
  },
  {
    dish: true,
    icon: FrenchFries01Icon,
    hue: 60,
    names: ["batata frita", "batata palha", "fritas", "fries", "french fries"],
  },
  {
    dish: true,
    icon: SoupIcon,
    hue: 45,
    names: [
      "sopa",
      "soup",
      "caldo",
      "canja",
      "broth",
      "stock",
      "chicken stock",
      "chicken broth",
      "beef stock",
      "fumet",
      "dashi",
      "consomê",
      "chowder",
      "bisque",
      "minestrone",
      "gazpacho",
      "vichyssoise",
      "velouté",
      "pho",
      "missoshiru",
    ],
  },
  {
    dish: true,
    icon: CookingPotIcon,
    hue: 30,
    names: [
      "curry",
      "tikka masala",
      "dal",
      "ensopado",
      "guisado",
      "cozido",
      "stew",
      "feijoada",
      "moqueca",
      "bobó",
      "picadinho",
      "chili",
      "goulash",
      "ragu",
      "estrogonofe",
      "strogonoff",
      "stroganoff",
    ],
  },
  {
    dish: true,
    icon: SaladIcon,
    hue: 150,
    names: ["salada", "salad", "coleslaw", "tabule", "tabbouleh", "caprese", "vinagrete"],
  },
  {
    dish: true,
    icon: SpaghettiIcon,
    hue: 80,
    names: [
      "macarrão",
      "macarrões",
      "macarronada",
      "espaguete",
      "spaghetti",
      "pasta",
      "penne",
      "fusilli",
      "farfalle",
      "talharim",
      "fettuccine",
      "linguine",
      "lasanha",
      "lasagna",
      "nhoque",
      "gnocchi",
      "ravioli",
      "tortellini",
      "canelone",
      "cannelloni",
      "orzo",
      "cuscuz",
      "couscous",
      "carbonara",
      "bolonhesa",
      "bolognese",
      "mac and cheese",
    ],
  },
  {
    dish: true,
    icon: NoodlesIcon,
    hue: 70,
    names: [
      "noodle",
      "rice noodles",
      "macarrão de arroz",
      "bifum",
      "lámen",
      "ramen",
      "miojo",
      "udon",
      "soba",
      "yakisoba",
      "pad thai",
      "lo mein",
      "chow mein",
    ],
  },
  {
    dish: true,
    icon: RiceBowl01Icon,
    hue: 85,
    names: [
      "arroz",
      "rice",
      "arbóreo",
      "arborio",
      "basmati",
      "risoto",
      "risotto",
      "paella",
      "biryani",
      "galinhada",
      "baião de dois",
      "bibimbap",
      "donburi",
    ],
  },
  {
    dish: true,
    icon: EggFriedIcon,
    hue: 85,
    names: [
      "ovo",
      "egg",
      "huevos",
      "omelete",
      "omelette",
      "omelet",
      "fritada",
      "frittata",
      "shakshuka",
      "shakshouka",
      "benedict",
    ],
  },
  {
    dish: true,
    icon: BbqGrillIcon,
    hue: 25,
    names: ["churrasco", "barbecue", "bbq", "espetinho", "espeto", "grelhado", "grilled", "kebab"],
  },
  {
    dish: true,
    icon: SoftDrink01Icon,
    hue: 55,
    names: [
      "suco",
      "juice",
      "refrigerante",
      "soda",
      "cola",
      "guaraná",
      "tônica",
      "tonic",
      "vitamina",
      "smoothie",
      "milkshake",
      "limonada",
      "lemonade",
    ],
  },
  {
    dish: true,
    icon: Coffee02Icon,
    hue: 45,
    names: ["café", "coffee", "espresso", "expresso", "cappuccino", "latte", "mocha", "macchiato"],
  },
]
